### ISSUE TITLE
Space in the title of a category caused an issue

### ISSUE THREAD

**Issue by roberthjack** [BelaPlatform/bela_newBlog#1]
To recreate visit https://disastrid.github.io/bela_newBlog/2016/11/28/saber/ and then click on the Sound Design Category under the main title.

**Comment by disastrid** [comment]
Fixed! See the readme. The highlights:

Your category title should be between quotation marks. 
The permalink should have a dash between each word, like: /category/sound-design
The file should be named with a dash between each word, like: sound-design.html
The category's image (which will be a jpg) should be named like this: sounddesign.jpg
