### ISSUE TITLE
Long lines in pre-formatted (```) boxes extend outside background

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela_newBlog#10]
e.g.:

<img width="1023" alt="screen shot 2017-01-11 at 03 43 39" src="https://cloud.githubusercontent.com/assets/4260604/21834826/2e18fa08-d7b0-11e6-8a45-ed51159cfcbd.png">

A possible solution would be to add
```
.highlighter-rouge{
  overflow-x: auto;
}
```
so that you obtain this: 

<img width="815" alt="screen shot 2017-01-11 at 03 43 30" src="https://cloud.githubusercontent.com/assets/4260604/21834832/38b0cfd6-d7b0-11e6-8436-97d5196d9249.png">

and you can scroll the box content horizontally.

Note that the next thing I would ask for is make it obvious that the content is scrollable (i.e.: always show scrollbar when there is something to scroll).

**Comment by disastrid** [comment]
`overflow-x: auto` should display a scroll bar if there is scrollable content - needs testing to make sure this is true in all browsers. (Implementing `overflow-x: scroll` isn't an option as this will add a scroll bar to all code elements.)

**Comment by giuliomoro** [comment]
These modern browsers think it is cool to hide the scrollbar by default, anyhow `overflow-x: auto` is the way to go. 
Done bfc7f3a.
