### ISSUE TITLE
Long category names are cropped in the side bar

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela_newBlog#2]
https://disastrid.github.io/bela_newBlog/category/instruments/
example:
<img width="1280" alt="screen shot 2016-11-29 at 02 16 55" src="https://cloud.githubusercontent.com/assets/4260604/20693979/ef28b9de-b5d9-11e6-8e26-88ad9a10d546.png">

**Comment by disastrid** [comment]
Fixed. I haven't tested on every conceivable platform so if you run into future problems let me know.
