### ISSUE TITLE
Sidebar flickers when moving mouse between adjacent post previews

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela_newBlog#3]
e.g.: on [this page](https://disastrid.github.io/bela_newBlog/category/instruments/] if you move your mouse between the top and the bottom post, the image in the sidebar will flicker. Is it because you can potentially have different pics in the sidebar for each project? That'd be great, so we could show here a preview of the post's image.

**Comment by disastrid** [comment]
Fixed.
