### ISSUE TITLE
How do I make a bold statement?

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela_newBlog#4]
Is there a way to make bold?

`*myBoldText*` and `_myItalicText_` both translate into an `<em>` tag which is rendered by default as italic.

I vote for `*this*` to render like **this**, for compatibility with github, but anything will do.

**Comment by giuliomoro** [comment]
Man, just use two stars and you'll be fine.

**Comment by disastrid** [comment]
:)

**Comment by giuliomoro** [comment]
Still the rendered text does not look very bold. Maybe a `bold` variant of the font should be used instead?

**Comment by disastrid** [comment]
Can you screenshot an example please?

**Comment by giuliomoro** [comment]
https://disastrid.github.io/bela_newBlog/2016/11/28/Bela-analogue-vs-audio/

scroll down to 
"String DAC: a string DAC is basically a long string of resistors all placed in series. "

can you tell that "String DAC" is bold? Here is what it looks like for me: not very obvious

<img width="962" alt="screen shot 2016-12-05 at 15 25 08" src="https://cloud.githubusercontent.com/assets/4260604/20890505/09c62702-baff-11e6-83cd-7957880d3429.png">
