### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela_newBlog#6]
See this nice table here:

  | Bits | Sample Rate | Level | Coupling | Conversion Latency | Internal aliasing filter?
| ---- | ---------- | ----- | -------- | ----------------- | --------
| Audio In | 16 | 44.1kHz | +/-1V (gain available) | AC | 0.39ms | yes
| Audio Out | 16 | 44.1kHz | +/-1V (gain available) | AC | 0.47ms | yes
| Analogue In | 16 | 22.05kHz x 8, 44.1kHz x 4, 88.2kHz x 2 | 0-4.096V | DC | < 10us | no
| Analogue Out | 16 | 22.05kHz x 8, 44.1kHz x 4, 88.2kHz x 2 | 0-5V | DC | < 10us | no

Unfortunately it does not look as nice [here](https://disastrid.github.io/bela_newBlog/2016/04/07/bela-analogue-vs-audio/), though it surely is interpreted as a table.

**Comment by giuliomoro** [comment]
It would be useful to have the lines at least (if not the alternating background)

**Comment by disastrid** [comment]
Table styles merged from Sample pattern library.
