### ISSUE TITLE
Images width

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela_newBlog#7]
Any easy way to have custom image width?
These are a bit too wide!

https://disastrid.github.io/bela_newBlog/2016/04/07/bela-analogue-vs-audio/

**Comment by disastrid** [comment]
As I said at the beginning, I have implemented responsive image widths. However I need to get on with the week of work that I forewent to do this development, and therefore I have not created every method of image handling. If you would like to write the HTML includes, please feel free, but please test it thoroughly across devices to make sure the CSS is sound.
