### ISSUE TITLE
Default text of each post pulls in headings and paragraph text without distinction

### ISSUE THREAD

**Issue by roberthjack** [BelaPlatform/bela_newBlog#9]
<img width="870" alt="screen shot 2017-01-08 at 19 00 07" src="https://cloud.githubusercontent.com/assets/11576979/21752690/e6073f2c-d5d4-11e6-96f7-5d2feee629d2.png">

**Comment by disastrid** [comment]
This isn't a bug in the existing design, it's that the system is being used differently than the use it was designed for. 

The layout is designed to pull in the first lines of content to form the excerpt. However, posts are being written with a strapline (or a featured describing sentence) at the beginning of each article. The layout is doing what it's supposed to - pulling in the first lines. Do you want the first sentence, therefore, to be excluded?

This does potentially introduce more bugs in the future, as each post will be written with a strapline, or risk exclusion. How essential are straplines, and should we commit to using them on every single blog post from here on out?

**Comment by giuliomoro** [comment]
Agreed that this should make us think about whether it is good to use the strapline at all (similar issue we are having also in the github Bela wiki).

Anyhow, I committed a solution if we want it: f9d418f

(courtesy of http://stackoverflow.com/questions/25802204/jekyll-filter-for-regex-substitution-in-content )

**Comment by giuliomoro** [comment]
Note this is on a separate branch, so will need to be merged if we are happy with it

**Comment by disastrid** [comment]
Thanks @giuliomoro. @roberthjack is a strapline really necessary? I'm fine to roll this change if we're going to commit to this long-term, but I'm not clear on the function straplines are serving, and therefore their viability/necessity in the long term. This is something to discuss at this week's meeting.

**Comment by roberthjack** [comment]
Haven't tested the other branch but if it ignores # in the text it is pulling then this is probably the best solution. This is just incase there is a strapline and then second sub-title before paragraph text starts. For example in the analog versus digital post. 

Whether or not straplines are a good thing to include more generally is something we should consider. I think they've probably ended up here from me porting posts from the old blog.bela.io

**Comment by giuliomoro** [comment]
Yes it only removes lines starting with `#`, so that if there is no heading, this has no effect.

**Comment by roberthjack** [comment]
Great, I'd say merge it in. I just removed all the straplines as, on
reflection, most of them were just repeating the heading text.
